### ISSUE TITLE
Double Release() risk

### ISSUE THREAD

**Issue by jgimenez** [sanketplus/go-mysql-lock#11]
If Release() is called twice, the second time will block forever. It would be preferable to return an error or ignore the second call.

A typical usage of the library would be like this:

```
lock, _ := locker.Obtain("foo")
// do something
lock.Release()
```

However, `lock.refresher()` may call `lock.Release()` if `PingContext()` fails. Therefore, it is impossible to know if it has already been called and write safe code that only calls once.

**Comment by sanketplus** [comment]
thanks @jgimenez for reporting the issue and apologies for the slightly delayed response. 

I think you're right, if `Release` is called again, the first line in the function which writes to a channel, will block.

I think we can use the `lostLockContext ` to determine if lock is already lost or released, and skip the steps, in order to not block. Happy to review a PR :)

**Comment by Areson** [comment]
Chiming in since I've also run into this. I think the issue with `lostLockContext` is that `lock.refresher` cancels the context _before_ calling `lock.Release`. Additionally there is no locking here so it's possible to end up in a race condition even if we try and adjust the ordering.

**Comment by sanketplus** [comment]
closing with the PR #12
